---
date: "2022-10-24"
design:
  spacing: 6rem
sections:
- block: resume-biography-3
  content:
    button:
      text: Download CV
      url: uploads/resume.pdf
    text: ""
    username: admin
  design:
    background:
      color: black
      image:
        filename: stacked-peaks.svg
        filters:
          brightness: 1
        parallax: false
        position: center
        size: cover
    css_class: dark
- block: markdown
  content:
    subtitle: ""
    text: "Use this area to speak to your mission. I'm a research scientist in the
      Moonshot team at DeepMind. I blog about machine learning, deep learning, and
      moonshots.\n\nI apply a range of qualitative and quantitative methods to comprehensively
      investigate the role of science and technology in the economy.\n\nPlease reach
      out to collaborate \U0001F603"
    title: "\U0001F4DA My Research"
  design:
    columns: "1"
- block: collection
  content:
    filters:
      featured_only: true
      folders:
      - publication
    title: Featured Publications
  design:
    columns: 2
    view: article-grid
  id: papers
- block: collection
  content:
    filters:
      exclude_featured: false
      folders:
      - publication
    text: ""
    title: Recent Publications
  design:
    view: citation
- block: collection
  content:
    filters:
      folders:
      - event
    title: Recent & Upcoming Talks
  design:
    columns: 1
    view: article-grid
  id: talks
- block: collection
  content:
    count: 5
    filters:
      author: ""
      category: ""
      exclude_featured: false
      exclude_future: false
      exclude_past: false
      publication_type: ""
      tag: ""
    offset: 0
    order: desc
    page_type: post
    subtitle: ""
    text: ""
    title: Recent News
  design:
    spacing:
      padding:
      - 0
      - 0
      - 0
      - 0
    view: date-title-summary
  id: news
- block: cta-card
  content:
    button:
      text: Get Started
      url: https://hugoblox.com/templates/
    text: |-
      This site is generated by Hugo Blox Builder - the FREE, Hugo-based open source website builder trusted by 250,000+ academics like you.

      <a class="github-button" href="https://github.com/HugoBlox/hugo-blox-builder" data-color-scheme="no-preference: light; light: light; dark: dark;" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star HugoBlox/hugo-blox-builder on GitHub">Star</a>

      Easily build anything with blocks - no-code required!

      From landing pages, second brains, and courses to academic resumés, conferences, and tech blogs.
    title: "\U0001F449 Build your own academic website like this"
  demo: true
  design:
    card:
      css_class: bg-primary-700
      css_style: ""
title: ""
type: landing
---
